api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']

    # The list of enabled patch formats. The first one will be the default.
    patch_formats:
        json: ['application/merge-patch+json']
    # formats:
    #     json: ['application/json']
    #     multipart:
    #         mime_types: ['multipart/form-data']
    swagger:
        versions: [3]
    collection:
        pagination:
            enabled: true
            items_per_page: 3
